### ISSUE TITLE
名前(ローマ字)の姓名の順番

### ISSUE THREAD

**Issue by crssnky** [kiridaruma/worldwitches-knowledge-base#3]
意図的でしたら閉じてください。  

インスタンスのURIにて、  
宮藤芳佳=>名 姓 (Yoshika Miyafuji)  
坂本美緒=>姓 名 (Sakamoto Mio)  
と順番が別々になってます。  

参考:https://www3.nhk.or.jp/news/html/20190521/k10011923541000.html

**Comment by kiridaruma** [comment]
issue建ててもらってたのに気が付かなくて、今気がつきました…
一応、 https://github.com/kiridaruma/worldwitches-knowledge-base/commit/1e19b870683ba641c768ef4f63228df2d013a58c のcommitで対応してるのでクローズします
issueありがとうございますー
気が付かなくて申し訳ない…
